language: java
addons:
  sonarcloud:
    organization: revaturelabs
    token:
      secure: etuGjV6bqBBghvjwJ5yOQB0m0d/ynuNS4rEm1ugnQynjyMqrlrs8gxl+o19SGjYPvXl4UQNKgTFmJtaQqsPgB83VlDusZZDDzOa4vkttseCy/+s1zPsTV4ZpcIcWBppPuiEFLZRabj7BuAopHHX0DV1/3kEOb1JgfdiTMSp/ocy6q2MFvQemKmb+lEgBvZHniNoEKp/jfjSSZ5IK0/gZlUCIPOXviMrH8xHq7qjSpYeabqDhF9+zA9rcD/ibpZoz+iqNmbR0/KIgyvoXAd4elvtmOmSk/yyGapt4iFNnvEtQFeNaO+Jf6PeWIbvyIQYLex9WRsoq9TVqfB6gctbBZEB9UUTTuKWncDSdPGVkshkmgRA3BTU7eWehp2LkCgf7T3d2i73jLPZAS2RnG12sq+Q3wl9rrjkH8+tdeWtcLjCz0eQNd+6YRUw7uMmKgJgMB5qmOnc5i1YJiVjpo1zLvqLTNnoZpm91rJBCPwAFZ0XcqzCaIJpfGYbEpXzcM+UtdRaoDWwcTv5nAPE+egYkRrls0zDbuwbbON15KERxjnbMZoyKc1w7yu5dOSHzL+lTzI6x4qmrPdGqkr3i+xZcwU4iCEEbdxy14GVecIhJ4SBtzMmGpCetI5mryWgAg/JrY7LqX3DHBcYCikwroHQaui3jTLiwydIj4BDxlCUnUxU=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: gt3x2P0AUvMwS+YJABDf2deZNql9+p05597Ze9Vr147nAPk8qrTxjPgleLGRdIp7kFSPfsir0PHoYRcU+yvN8+300mf9Qmu4yAqQ62WlU9UnHtGecvHX4cDzR7pEb1UwF/Rume5Xyce0P/2Ys0TSnLiAJm93lLwmgcGsVTJPF4x/FJ6Nui7tUc1WoXkeQAT2dLAq7tL9hGMe0W9OMYGt5/gnDRxxb3l/Lj8rXP73xJ8uvscMCRKlvh2BqI1PgXT+h9AapkkgpL7ou7iyrw2TYOPsiVydrDb595IaVaYW8pFSk5gYWOXkY3Bu87Nzw//gQXV8/sb/rYLzn1RAMb/3yuODq/xlnbsu7vVjWuh8THkRD/H8msrvncsWWDKGXSznZ0mmWhCdKVPiFVsnd/AQ2DNMuRcfQYzZIlcmW9aJjXEoH75mnWwcMTwlSJpfXS9uYCNRUrGY534yekCJsUSC+4ekB4tsMZWJjk+Qn1OgD2/URKsVHTpODMKCqUJjnal0qAfY1yCX4AqSyp1HlbNtImZoGfn3Ja+11TUxOXiLNu5j7yE65y8GMKflRuI51sTeeToFV+/nIIc8SH3ndzCTxZxa4KSo+RJgMyLGjg0PuEOK6fGsc+caewtEX1D1vA5kpw/Ez01XpGJn1XzN1moUFAbzZxxNOH3XBDCUTLFp6Ik=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-curriculum-service
    branch: develop
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
