language: java
deploy:
  skip_cleanup: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: email@bryton.io
  password:
    secure: XhY5i5iLHN3waFw8bRqlU/EjxOGrWZqnqFCfayW+lAXAajQIh4YxjawKjbuWPjd5+cmXipMq7c68CHxTY8rx0G7VIlf2yrNuKUDAF07/BfCErNH1Ls97f6TgCTBlnxNjAz4lqbNfkSx+FhNTshcCSbs3DlLEzNBuz7uUsjBPtAvAJZDoRaaj7nkAV9ZBPIgoMPbJv+QOsAtQbiOWRxA70Egsv7D3xNu/iQjcWhLfKS6dp80zXewLVIj8eNnPNikh5aORE4n65Z699ZfSXyOypcYF3e/TWvbVlF2YOKUAXMTBd+4OZcZhAJwH4i1kmYEWM+ZcGun2Hz3QMhyYKuigwO3R8pkq67REamUBbgRgYP9tgcf9cOyXQdNI6z5S0JIk2bv7FFd+PZDpRT//lgt12QPnaEV8SK1X6JQ5w6hGofqDlaCa8UK0aN2CvO9Y4VVvbWnvHVAC5yW3rCTD+aBOlX3+AxelU7pDHkG3+trRbAfs5Fo4LPMG+rMdy/SJh2sd6BmGbhMexJI9VAMPgt3RQT5k9qqe3LN118MLlBvzPHJWisc8jDU7ac66WYVtLZKxX523ALq9FkwJqeM4Q5flqqs2Mt+o2x/NTnDKlsV1ljQ4ix2sCdddPjl1cYgfLGbhpzhczMzovtVzCMzVoaC7rretkVC4RqII2yF40HTMRUQ=
  organization: august-duet.org
  space: development
  on:
    repo: revaturelabs/hydra-curriculum-service
    branch: develop
